# -*- coding: utf-8 -*-
"""[GRIDS4ALL]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zPLfwyVQzVx8o92sdRdH5F2N2EwiZeK
"""

import pandas as pd
import geopandas as gpd
import math

input_file = "/content/MINISTRY OF COLLECTIVITY - Sheet1.csv" # @param {"type":"string"}
data=pd.read_csv(input_file)

data_geospatial=data.dropna(axis=0,subset=data.columns[2]).reset_index()

data_geospatial[['latitude','longitude']]=data_geospatial[data_geospatial.columns[3]].str.split(',',expand=True).dropna().astype(float)

gdf = gpd.GeoDataFrame(
    data_geospatial, geometry=gpd.points_from_xy(data_geospatial.longitude, data_geospatial.latitude), crs="EPSG:4326"
)

gdf.plot()

gdf.to_file("output.geojson", driver='GeoJSON')

